# Generated by Django 5.2.3 on 2025-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='availability_date',
            field=models.DateField(blank=True, help_text='When can you start?', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications (one per line)'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='expected_salary',
            field=models.CharField(blank=True, help_text='Expected salary range', max_length=50),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('expert', 'Expert Level (10+ years)')], default='entry', max_length=10),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Current or desired job title', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages you speak (e.g., English, Spanish)', max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to your portfolio or personal website'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='remote_work_preference',
            field=models.BooleanField(default=False, help_text='Interested in remote work opportunities'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='willing_to_relocate',
            field=models.BooleanField(default=False, help_text='Willing to relocate for the right opportunity'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional bio about yourself'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills separated by commas'),
        ),
    ]
